language: c
compiler:
  - gcc
before_install:
- cd ../
- git clone https://github.com/cpputest/cpputest.git
- cd cpputest
- ./autogen.sh
- ./configure
- make
- sudo make install
- cd ../
- ls

script: make && make test 
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec